### PR TITLE
Add .pop() and .shift() tests

### PR DESCRIPTION
**Pull request by jhermsmeier**
Connects to #1

### CODE REVIEW

**Comment by lurch** [comment]
LGTM. I guess it wouldn't hurt to have `assert.strictEqual( pipeline.length, 2 )` before doing any popping or shifting?

**Comment by jhermsmeier** [comment]
> I guess it wouldn't hurt to have assert.strictEqual( pipeline.length, 2 ) before doing any popping or shifting?

Mildly paranoid, but added those ;)

**Comment by lurch** [comment]
Thanks. Something else 'paranoid' I've just thought of - before doing the popping and shifting could you `assert.notStrictEqual(stream1, stream2)` ?

**Comment by jhermsmeier** [comment]
> assert.notStrictEqual(stream1, stream2)

If that would throw then the runtime would be fundamentally broken, as two instances of a thing should never be the same object. I don't think we'd need to test that ;)

**Comment by lurch** [comment]
...I was just thinking that if you (accidentally) did `stream1 = stream2`, then you'd be unable to differentiate the behaviour of the `pop` and `shift` tests ;)  (i.e. either function would pass the other's tests)
But yeah that's probably more paranoid than needed :)

**Review by jviotti — APPROVED** [review]

**Pull request merged**
